!Example Banlist
--EndDate 2005-07-27
$whitelist
#forbidden
82301904 0 --Chaos Emperor Dragon - Envoy of the End
#limited
7902349 1 --Left Arm of the Forbidden One
#semi-limited
18318842 2 --Abyss Soldier
#whitelist
32864 3 --The 13th Grave
